version: '3'
services:
  web:
    image: nginx:1.13.5-alpine
    container_name: nginx-1
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/app/app/public:/var/www/html

  app:
    build: ./app
    container_name: app-1
    env_file: .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ./data/app/app:/var/www/html

  db:
    build: ./db
    container_name: db-1
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db-data-1:/var/lib/mysql
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db-data-1: